spring.application.name=eureka-server
#setting server port number
server.port=8761

# making not to register itself 
eureka.client.register-with-eureka=false
# since it's not a client no need fetch register details
eureka.client.fetch-registry=false